
import { Inter } from "next/font/google";
import "./globals.css";
import ProviderContext from "./contex/page";
// import Navbar from "./navbar/page";
// import Footer from "./footer/page";
// import Mobile from "./mobileApp/page";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
    

        <ProviderContext>
          <Suspense>

          
        {children}
          </Suspense>

        </ProviderContext>
        
       

      
      </body>
    </html>
  );
}
